[package]
name = "carbon"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6.17"
serde = { version = "1.0.160", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"
anyhow = "1.0.70"
async-trait = "0.1.68"
bollard = "0.14.0"
